Assert correct elements are removed from hashes larger than limit.
open-telemetry/opentelemetry-ruby pull request #1535
Opened 2023-10-27 21:18 UTC by ptolts

Adds missing test coverage for Tracestates larger than 32.

2023-10-31 17:49 UTC, fbogsany requested changes
This is technically incorrect. From https://github.com/open-telemetry/opentelemetry-ruby/pull/1533#issuecomment-1783535817

> Followup: the [W3C `trace-context` spec](https://www.w3.org/TR/trace-context/#tracestate-limits) states:
> 
> > In a situation where `tracestate` needs to be truncated due to size limitations, the vendor _MUST_ truncate whole entries. Entries larger than 128 characters long _SHOULD_ be removed first. Then entries _SHOULD_ be removed starting from the end of `tracestate`. Note that other truncation strategies like safe list entries, blocked list entries, or size-based truncation _MAY_ be used, but are highly discouraged. Those strategies decrease the interoperability of various tracing vendors.

Our implementation is wrong and we should remove entries from the end rather than the start (and, of course, we should remove entries > 128 characters first).

2023-11-01 21:10 UTC, ptolts commented
I'll close, thanks Bogs.

2023-11-02 13:43 UTC, fbogsany commented
@ptolts could you please click the link in https://github.com/open-telemetry/opentelemetry-ruby/pull/1535#issuecomment-1783522860 to authorize the CLA?

2023-11-02 13:45 UTC, fbogsany commented on api/test/opentelemetry/trace/tracestate_test.rb
> +      _(output_hash).must_equal(input_hash.drop(1).to_h)
```suggestion
      _(output_hash).must_equal(input_hash.first(32).to_h)
```

2024-02-20 21:07 UTC, kaylareopelle commented
Hi, @ptolts! Checking in on this PR. Would you be open to signing the CLA?

2024-04-21 01:47 UTC, closed without merging