docs: add documentation for Metrics API instruments
open-telemetry/opentelemetry-ruby pull request #1720
Opened 2024-09-04 19:16 UTC by xuan-cao-swi

Closes https://github.com/open-telemetry/opentelemetry-ruby/issues/1707

2024-09-12 23:54 UTC, kaylareopelle requested changes

2024-09-20 00:16 UTC, kaylareopelle approved these changes
Thank you!

2024-10-16 22:54 UTC, hannahramadan commented on metrics_api/lib/opentelemetry/metrics/meter.rb
> +      # Counter is a synchronous Instrument which supports non-negative increments.
What do we think about hyperlinking to the docs? I noticed some of them provide additional links and examples that may be useful. Could go either way!

```suggestion
      # {https://opentelemetry.io/docs/specs/otel/metrics/api/#counter Counter} is a synchronous Instrument which supports non-negative increments.
```

2025-01-08 20:36 UTC, kaylareopelle commented on metrics_api/lib/opentelemetry/metrics/meter.rb
> +
My bad, when I fixed the merge conflict, I added some unnecessary whitespace.
```suggestion
```

2025-01-08 21:15 UTC, kaylareopelle commented on metrics_api/lib/opentelemetry/metrics/meter.rb
> +      # @return [nil] after creation of up_down_counter, it will be stored in instrument_registry
```suggestion

      # UpDownCounter is a synchronous Instrument which supports increments and decrements.
      #
      # With this api call:
      #
      #   items_counter = meter.create_up_down_counter("store.inventory",
      #                                                description: "the number of the items available",
      #                                                unit: "s")
      #
      # @param name [String] the name of the up_down_counter
      # @param unit [optional String] an optional string provided by user.
      # @param description [optional String] an optional free-form text provided by user.
      #
      # @return [nil] after creation of up_down_counter, it will be stored in instrument_registry
```

2025-01-08 22:12 UTC, merged