feat: introduce sem_comv stability mode
open-telemetry/opentelemetry-ruby pull request #1728
Opened 2024-09-12 22:58 UTC by hannahramadan

2024-09-17 16:05 UTC, hannahramadan commented on semantic_conventions/lib/opentelemetry/semantic_conventions/stability_mode.rb
> +    # stability_mode.set_http_url(result, 'https://example.com')
Made some updates! https://github.com/open-telemetry/opentelemetry-ruby/pull/1728/commits/36cfd9a3b49bb48520e6e0f60c588e7f37b1fa9e

2024-10-01 16:54 UTC, kaylareopelle commented
Link to instrumentation that uses this PR: https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/1166

2024-10-02 22:08 UTC, kaylareopelle requested changes

2024-10-02 22:08 UTC, kaylareopelle commented on semantic_conventions/lib/opentelemetry/semantic_conventions/stability_mode.rb
> +          http_set_sability_mode(opt_in_list) if opt_in_list
```suggestion
          http_set_stability_mode(opt_in_list) if opt_in_list
```

2024-10-02 22:08 UTC, kaylareopelle commented on semantic_conventions/lib/opentelemetry/semantic_conventions/stability_mode.rb
> +      def http_set_sability_mode(opt_in_list)
```suggestion
      def http_set_stability_mode(opt_in_list)
```

2025-06-20 22:16 UTC, closed without merging