fix: update references to logging exporter
open-telemetry/opentelemetry-ruby pull request #1731
Opened 2024-09-20 17:36 UTC by codeboten

This exporter has been replaced by the debug exporter and will be removed soon

2024-09-20 19:21 UTC, kaylareopelle requested changes
Thank you for this PR, @codeboten! 

I think the metrics example updates are great. The `otel-collector` example updates don't work quite yet.

The version of the collector in `examples/otel-collector/.env` predates the debug exporter. It currently uses 0.35.0. However, when we update to the earliest version with the debug exporter, [0.86.0](https://github.com/open-telemetry/opentelemetry-collector/blob/main/CHANGELOG.md#v100-rcv0015v0860), we hit problems with the Jaeger exporter no longer being present in the collector. 

I've tried a few things to fix this, including following [the documentation to update Jaeger](https://opentelemetry.io/blog/2023/jaeger-exporter-collector-migration/), but couldn't get it to work. It feels serendipitous that you're the author of that doc and of this PR.

I totally get it if this was just a quick PR and you don't have more time to spend on this problem. If you do have more time to spend, I would appreciate your help getting this example to work on a newer version of the collector.

Happy to send along more details on my exploits if you have the bandwidth!

2024-09-20 19:34 UTC, codeboten commented
@kaylareopelle i've updated the example to use v0.109.0 of the collector, take a look and see if it works on your end. I tested it locally and was able to see a trace in jaeger

2024-09-20 22:10 UTC, kaylareopelle approved these changes
Thank you, @codeboten! This works for me too 😄

2024-10-01 17:10 UTC, mwear approved these changes

2024-10-01 17:44 UTC, merged