Added README for concurrent ruby
open-telemetry/opentelemetry-ruby pull request #383
Opened 2020-09-15 17:32 UTC by eunice98k

This PR adds documentation for Concurrent Ruby, closing [#234.](https://github.com/open-telemetry/opentelemetry-ruby/issues/234)

I added a README describing the Concurrent ruby gem, installation methods and its license.

2020-09-15 19:48 UTC, ericmustin requested changes
2 extremely minor changes. otherwise this LGTM, nice work, thanks @eunice98k !

2020-09-15 19:48 UTC, ericmustin commented on instrumentation/concurrent_ruby/README.md
> +The OpenTelemetry Concurrent Ruby gem is a community maintained instrumentation for the [Concurrent Ruby][concurentruby-home]. This is a concurrency toolkit inspired from various languages and classi
```suggestion
The OpenTelemetry Concurrent Ruby gem is a community maintained instrumentation for the [Concurrent Ruby][concurrent-ruby-home]. This is a concurrency toolkit inspired from various languages and classic concurrency patterns. 
```

2020-09-15 19:48 UTC, ericmustin commented on instrumentation/concurrent_ruby/README.md
> +[concurentruby-home]: https://github.com/ruby-concurrency/concurrent-ruby
```suggestion
[concurrent-ruby-home]: https://github.com/ruby-concurrency/concurrent-ruby
```

2020-09-15 21:11 UTC, ericmustin approved these changes
👍

2020-09-15 21:19 UTC, alolita approved these changes
ltgm

2020-09-16 11:35 UTC, fbogsany approved these changes

2020-09-16 11:36 UTC, merged